### ISSUE TITLE
We could add black theme mode

### ISSUE THREAD

**Issue by himanshujaidka** [manikandanraji/youtubeclone-frontend#3]
We have to give the option to the user whether they want to watch this in dark mode or light mode @manikandanraji

**Comment by Theyvetriedtokillmemywholelife** [comment]
might as well just make it dark mode. since I am the user ya'll are hacking. I would love for someone to justify why its okay to use MIT Apache and Darwin kernel root-kits so they can deploy constraints to  someone's online business they built from the ground up in a wheelchair. At this rate, there will be no more small business. Hey, at least there wont be anymore competition! someone should email me (without headers or footers or bitmap)
jaystyles1983@yahoo.com
